# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "172.16.10.103"
  config.vm.hostname = "rancher"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "rancher"
     vb.cpus = 2
     vb.memory = "4096"
  end

  # Run file install-docker-kube.sh after create box
  config.vm.provision "shell", path: "./../install-docker-kube.sh"

  # Run shell commands
  config.vm.provision "shell", inline: <<-SHELL
    # Set pass 123 for root and allow ssh
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd
# Output to file /etc/hosts
cat >>/etc/hosts<<EOF
172.16.10.100 master.xtl
172.16.10.101 worker1.xtl
172.16.10.102 worker2.xtl
EOF

  SHELL
end
